"""Phase 4 — document-level ACL on the KB index (domain-AGNOSTIC).

The mechanism enforces a classification; it does NOT invent one. There is **no
classification logic in this code** — no markers, no component names, no heuristics.
Each document's sensitivity is *data the owner provides*, exactly like the corpus:

  • An external classification map (``COCKPIT_ACL_CLASSIFICATION`` → a JSON file,
    gitignored) declares ``{ document-key : tier-name }`` — maintained by the data
    owner, or generated by wiki_builder by inheriting each source repo's access.
  • The tier name resolves to an Entra group via settings (``public/internal/
    confidential`` → group object-IDs from infra/entra), so a tenant maps the tiers to
    its own groups without touching code.
  • Documents absent from the map fall to ``cockpit_acl_default_tier`` — default
    **fail-closed** (the most restrictive tier), so nothing leaks by omission.

`_component()` is *identity extraction* (deterministic parse of the blob naming
convention), not classification — it just yields the key looked up in the owner's map.

Run from apps/backend after groups exist (infra/entra) and the classification file is set:
    COCKPIT_ACL_CLASSIFICATION=/path/to/classification.json uv run python -m app.knowledge.acl_setup
"""

from __future__ import annotations

import json
import os
import re
import urllib.request
from pathlib import Path

from azure.identity import DefaultAzureCredential

from app.core.settings import settings

_API = "2025-08-01-preview"
_INDEX = "cockpit-docbundles-ks-index"
_SEARCH_SCOPE = "https://search.azure.com/.default"


def _tier_groups() -> dict[str, str]:
    """Tier name → Entra group object-ID (the tenant's own groups, from settings)."""
    return {
        "public": settings.cockpit_acl_public_group,
        "internal": settings.cockpit_acl_internal_group,
        "confidential": settings.cockpit_acl_confidential_group,
    }


def _component(blob_url: str) -> str:
    """Deterministic identity from the blob naming convention (NOT classification).

    `<component>(-v<ver>)?__<page>.md` → `<component>`; `source__<NAME>__…` → `source__<NAME>`.
    This is just the key the owner's classification map is keyed on."""
    name = re.sub(r"\.md\d*$", "", blob_url.rsplit("/", 1)[-1])
    head = name.split("__")[0]
    if head == "source" and "__" in name:
        return "source__" + name.split("__")[1]
    return re.sub(r"-v[\d.]+.*$", "", head)


def _load_classification() -> dict[str, str]:
    """Owner-provided { document-key : tier-name }. External + gitignored, like the corpus."""
    path = os.environ.get("COCKPIT_ACL_CLASSIFICATION", settings.cockpit_acl_classification)
    if not path:
        return {}
    return json.loads(Path(path).expanduser().read_text(encoding="utf-8"))


def _req(token: str, method: str, path: str, body: dict | None = None) -> dict | None:
    req = urllib.request.Request(
        f"{settings.azure_search_endpoint}/{path}", method=method,
        headers={"Authorization": f"Bearer {token}", "Content-Type": "application/json"},
    )
    resp = urllib.request.urlopen(req, json.dumps(body).encode() if body is not None else None, timeout=90)
    try:
        return json.load(resp)
    except Exception:  # noqa: BLE001 — 204 No Content on index PUT
        return None


def _set_option(token: str, index: dict, state: str) -> None:
    index = {k: v for k, v in index.items() if not k.startswith("@odata")}
    index["permissionFilterOption"] = state  # "enabled" | "disabled"
    _req(token, "PUT", f"indexes/{_INDEX}?api-version={_API}", index)


def setup_acl() -> None:
    tier_groups = _tier_groups()
    if not all(tier_groups.values()):
        raise SystemExit("Set COCKPIT_ACL_{PUBLIC,INTERNAL,CONFIDENTIAL}_GROUP first (infra/entra).")
    classification = _load_classification()
    default_tier = settings.cockpit_acl_default_tier  # fail-closed by default
    if not classification:
        print(f"⚠️  no classification map (COCKPIT_ACL_CLASSIFICATION) — every doc → '{default_tier}'.")

    token = DefaultAzureCredential().get_token(_SEARCH_SCOPE).token
    index = _req(token, "GET", f"indexes/{_INDEX}?api-version={_API}")
    assert index is not None

    if "groups" not in {f["name"] for f in index["fields"]}:
        index["fields"].append({
            "name": "groups", "type": "Collection(Edm.String)",
            "filterable": True, "retrievable": True, "searchable": False,
            "permissionFilter": "groupIds",
        })
        _set_option(token, index, "enabled")
        index = _req(token, "GET", f"indexes/{_INDEX}?api-version={_API}")
        assert index is not None
        print("✓ permission field 'groups' added")

    # Populate under a disabled window (docs with no group are invisible when enforced).
    _set_option(token, index, "disabled")
    docs, skip = [], 0
    while True:
        page = _req(token, "GET", f"indexes/{_INDEX}/docs?api-version={_API}&search=*&$select=uid,blob_url&$top=1000&$skip={skip}")
        rows = (page or {}).get("value", [])
        if not rows:
            break
        docs += rows
        skip += len(rows)
        if len(rows) < 1000:
            break

    from collections import Counter
    tally: Counter[str] = Counter()
    batch: list[dict] = []
    for d in docs:
        tier = classification.get(_component(d.get("blob_url", "")), default_tier)
        group = tier_groups.get(tier, tier_groups[default_tier])
        tally[tier] += 1
        batch.append({"@search.action": "mergeOrUpload", "uid": d["uid"], "groups": [group]})
        if len(batch) >= 500:
            _req(token, "POST", f"indexes/{_INDEX}/docs/index?api-version={_API}", {"value": batch})
            batch = []
    if batch:
        _req(token, "POST", f"indexes/{_INDEX}/docs/index?api-version={_API}", {"value": batch})

    _set_option(token, index, "enabled")
    print(f"✓ stamped {len(docs)} docs by owner-declared tier {dict(tally)}; trimming ENABLED")


if __name__ == "__main__":
    setup_acl()
